/**
 * Created by liuzhengdong on 16/9/21.
 */

export const STORE_SESSION = "STORE_SESSION"
export const FLUSH_SESSION = "FLUSH_SESSION"

export const OPEN_MESSAGE = "OPEN_MESSAGE"
export const CLOSE_MESSAGE = "CLOSE_MESSAGE"

export const LOGIN = "LOGIN"
export const LOGIN_AJAX_START = "LOGIN_AJAX_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const SET_AUTH = "SET_AUTH"
export const DESTORY_AUTH = "DESTORY_AUTH"

export const GET_ACCOUNTS = "GET_ACCOUNTS"
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS"
export const GET_ACCOUNTS_FAILURE = "GET_ACCOUNTS_FAILURE"
export const POST_ACCOUNTS = "POST_ACCOUNTS"
export const POST_ACCOUNTS_SUCCESS = "POST_ACCOUNTS_SUCCESS"
export const POST_ACCOUNTS_FAILURE = "POST_ACCOUNTS_FAILURE"
